name: Deploy to Cloud Run

on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE: us-central1-docker.pkg.dev/innate-entry-462509-f5/order-service/orders:${{ github.sha }}
      REGION: us-central1
      PROJECT_ID: innate-entry-462509-f5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE .

      - name: Push Docker image to Artifact Registry
        run: |
          echo "Pushing Docker image..."
          docker push $IMAGE

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE: us-central1-docker.pkg.dev/innate-entry-462509-f5/order-service/orders:${{ github.sha }}
      REGION: us-central1
      SERVICE: orders-service
      PROJECT_ID: innate-entry-462509-f5
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run..."
          gcloud run deploy $SERVICE \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
        env:
          CLOUDSDK_CORE_PROJECT: ${{ env.PROJECT_ID }}
          CLOUDSDK_RUN_REGION: ${{ env.REGION }}

      - name: Post-deployment info
        run: |
          echo "Deployment complete."
          gcloud run services describe $SERVICE --region $REGION --format='value(status.url)'
